//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChatDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExistingUser
    {
        public ExistingUser()
        {
            this.StoredMessages = new HashSet<StoredMessage>();
            this.StoredMessages1 = new HashSet<StoredMessage>();
        }
    
        public int UserId { get; set; }
        public string Name { get; set; }
        public string UserName { get; set; }
        public Nullable<System.DateTime> LastConnection { get; set; }
        public Nullable<bool> IsConnected { get; set; }
    
        public virtual ICollection<StoredMessage> StoredMessages { get; set; }
        public virtual ICollection<StoredMessage> StoredMessages1 { get; set; }
    }
}
