//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChatDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class StoredMessage
    {
        public int MessageId { get; set; }
        public string MessageText { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<System.DateTime> SentDate { get; set; }
        public Nullable<int> RecipientID { get; set; }
    
        public virtual ExistingUser ExistingUser { get; set; }
        public virtual ExistingUser ExistingUser1 { get; set; }
    }
}
